apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-demo
  namespace: kube-system
  labels:
    app: mysql-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-demo
  template:
    metadata:
      labels:
        app: mysql-demo
    spec:
      containers:
      - name: mysql
        image: 'mysql:5.6.41'
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/mysql/lib
        #resources:
         # limits:
          #  cpu: 500Mi
           # memory: 1Gi
          #requests:
           # cpu: 500Mi
           # memory: 1Gi
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
              claimName: mysqlpvc

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-wayne
  name: mysql-wayne
  namespace: kube-system
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-wayne
